import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import { UserProvider } from "../app/userContext";
import { getProfile } from "./api/api";
import type { User } from "./types";
import { Toaster } from "@/components/ui/sonner"


// Chargement des polices Google
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  const user : User | null = await getProfile()


  return (
    <html lang="fr">
      <body className={`${inter.variable} ${manrope.variable} font-sans antialiased`}>
        <UserProvider initialUser={user}>{children}</UserProvider>
         <Toaster  position="top-right"
          theme="dark"
           richColors/>
      </body>
    </html>
  );
}
